package com.mobileslicer.profiles

import org.json.JSONArray
import org.json.JSONObject

private const val ORCA_MIN_IRONING_SPACING_MM = 0.1f
private const val ORCA_DEFAULT_SUPPORT_IRONING_FLOW_PERCENT = 10f

internal fun normalizedProcessSeamGap(value: String): String {
    val trimmed = value.trim()
    return when {
        trimmed.isBlank() -> DEFAULT_SEAM_GAP
        trimmed == "10%" -> DEFAULT_SEAM_GAP
        else -> trimmed
    }
}

internal fun JSONObject.putNativeProcessConfiguration(process: ProcessProfile): JSONObject = apply {
    put("layer_height", process.layerHeightMm.toDouble())
            .put("initial_layer_print_height", process.firstLayerHeightMm.toDouble())
            .put("first_layer_height", process.firstLayerHeightMm.toDouble())
            .put("initial_layer_speed", process.firstLayerPrintSpeedMmPerSec.toDouble())
            .put("initial_layer_infill_speed", process.firstLayerInfillSpeedMmPerSec.toDouble())
            .put("initial_layer_travel_speed", "${process.firstLayerTravelSpeedPercent}%")
            .put("first_layer_print_speed", process.firstLayerPrintSpeedMmPerSec.toDouble())
            .put("first_layer_infill_speed", process.firstLayerInfillSpeedMmPerSec.toDouble())
            .put("initial_layer_travel_speed_percent", process.firstLayerTravelSpeedPercent)
            .put("slow_down_layers", process.slowDownLayers)
            .put("initial_layer_acceleration", process.initialLayerAccelerationMmPerSec2.toDouble())
            .put("initial_layer_jerk", process.initialLayerJerkMmPerSec.toDouble())
            .put("first_layer_flow_ratio", process.firstLayerFlowRatio.toDouble())
            .put("print_extruder_id", process.printExtruderId)
            .put("print_extruder_variant", process.printExtruderVariant)
            .put("outer_wall_speed", process.outerWallSpeedMmPerSec.toDouble())
            .put("inner_wall_speed", process.innerWallSpeedMmPerSec.toDouble())
            .put("top_surface_speed", process.topSurfaceSpeedMmPerSec.toDouble())
            .put("travel_speed", process.travelSpeedMmPerSec.toDouble())
            .put("default_acceleration", process.defaultAccelerationMmPerSec2.toDouble())
            .put("outer_wall_acceleration", process.outerWallAccelerationMmPerSec2.toDouble())
            .put("inner_wall_acceleration", process.innerWallAccelerationMmPerSec2.toDouble())
            .put("top_surface_acceleration", process.topSurfaceAccelerationMmPerSec2.toDouble())
            .put("sparse_infill_acceleration", process.sparseInfillAccelerationMmPerSec2.toDouble())
            .put("internal_solid_infill_acceleration", process.internalSolidInfillAcceleration)
            .put("travel_acceleration", process.travelAccelerationMmPerSec2.toDouble())
            .put("accel_to_decel_enable", process.accelToDecelEnable)
            .put("accel_to_decel_factor", process.accelToDecelFactorPercent)
            .put("default_junction_deviation", process.defaultJunctionDeviationMm.toDouble())
            .put("default_jerk", process.defaultJerkMmPerSec.toDouble())
            .put("inner_wall_jerk", process.innerWallJerkMmPerSec.toDouble())
            .put("infill_jerk", process.infillJerkMmPerSec.toDouble())
            .put("top_surface_jerk", process.topSurfaceJerkMmPerSec.toDouble())
            .put("travel_jerk", process.travelJerkMmPerSec.toDouble())
            .put("inner_wall_flow_ratio", process.innerWallFlowRatio.toDouble())
            .put("outer_wall_jerk", process.outerWallJerkMmPerSec.toDouble())
            .put("outer_wall_flow_ratio", process.outerWallFlowRatio.toDouble())
            .put("top_solid_infill_flow_ratio", process.topSolidInfillFlowRatio.toDouble())
            .put("bottom_solid_infill_flow_ratio", process.bottomSolidInfillFlowRatio.toDouble())
            .put("overhang_1_4_speed", process.overhang1_4Speed)
            .put("overhang_2_4_speed", process.overhang2_4Speed)
            .put("overhang_3_4_speed", process.overhang3_4Speed)
            .put("overhang_4_4_speed", process.overhang4_4Speed)
            .put("enable_overhang_speed", process.enableOverhangSpeed)
            .put("slowdown_for_curled_perimeters", process.slowdownForCurledPerimeters)
            .put("overhang_flow_ratio", process.overhangFlowRatio.toDouble())
            .put("dont_slow_down_outer_wall", process.dontSlowDownOuterWall)
            .put("bridge_acceleration", process.bridgeAcceleration.ifBlank { "50%" })
            .put("bridge_speed", process.bridgeSpeedMmPerSec.toDouble())
            .put("small_perimeter_speed", process.smallPerimeterSpeedMmPerSec.toDouble())
            .put("small_perimeter_threshold", process.smallPerimeterThresholdMm.toDouble())
            .put("bridge_angle", process.bridgeAngleDegrees.toDouble())
            .put("bridge_density", process.bridgeDensityPercent)
            .put("bridge_flow", process.bridgeFlowRatio.toDouble())
            .put("bridge_no_support", process.bridgeNoSupport)
            .put("thick_internal_bridges", process.thickInternalBridges)
            .put("enable_extra_bridge_layer", process.extraBridgeLayer.configValue)
            .put("internal_bridge_angle", process.internalBridgeAngleDegrees.toDouble())
            .put("internal_bridge_density", process.internalBridgeDensityPercent)
            .put("internal_bridge_flow", process.internalBridgeFlowRatio.toDouble())
            .put("internal_bridge_speed", process.internalBridgeSpeed.ifBlank { "150%" })
            .put("internal_bridge_fan_speed", process.internalBridgeFanSpeed.ifBlank { "100%" })
            .put("internal_bridge_support_thickness", process.internalBridgeSupportThickness.ifBlank { "50%" })
            .put("max_volumetric_extrusion_rate_slope", process.maxVolumetricExtrusionRateSlope.toDouble())
            .put("max_volumetric_extrusion_rate_slope_segment_length", process.maxVolumetricExtrusionRateSlopeSegmentLengthMm.toDouble())
            .put("extrusion_rate_smoothing_external_perimeter_only", process.extrusionRateSmoothingExternalPerimeterOnly)
            .put("sparse_infill_speed", process.sparseInfillSpeedMmPerSec.toDouble())
            .put("internal_solid_infill_speed", process.internalSolidInfillSpeedMmPerSec.toDouble())
            .put("gap_infill_speed", process.gapInfillSpeedMmPerSec.toDouble())
            .put("top_shell_layers", process.topShellLayers)
            .put("bottom_shell_layers", process.bottomShellLayers)
            .put("top_shell_thickness", process.topShellThicknessMm.toDouble())
            .put("bottom_shell_thickness", process.bottomShellThicknessMm.toDouble())
            .put("top_surface_density", process.topSurfaceDensityPercent)
            .put("bottom_surface_density", process.bottomSurfaceDensityPercent)
            .put("seam_position", process.seamPosition.configValue)
            .put("staggered_inner_seams", process.staggeredInnerSeams)
            .put("seam_gap", normalizedProcessSeamGap(process.seamGap))
            .put("seam_slope_type", process.seamScarfType.configValue)
            .put("seam_slope_conditional", process.seamScarfConditional)
            .put("scarf_angle_threshold", process.scarfAngleThresholdDegrees)
            .put("scarf_overhang_threshold", process.scarfOverhangThresholdPercent)
            .put("scarf_joint_speed", process.scarfJointSpeed.ifBlank { "100%" })
            .put("scarf_joint_flow_ratio", process.scarfJointFlowRatio.toDouble())
            .put("seam_slope_start_height", process.seamScarfStartHeight)
            .put("seam_slope_entire_loop", process.seamScarfEntireLoop)
            .put("seam_slope_min_length", process.seamScarfMinLengthMm.toDouble())
            .put("seam_slope_steps", process.seamScarfSteps)
            .put("seam_slope_inner_walls", process.seamScarfInnerWalls)
            .put("role_based_wipe_speed", process.roleBasedWipeSpeed)
            .put("wipe_speed", process.wipeSpeed.ifBlank { "80%" })
            .put("wipe_on_loops", process.wipeOnLoops)
            .put("wipe_before_external_loop", process.wipeBeforeExternalLoop)
            .put("has_scarf_joint_seam", process.hasScarfJointSeam)
            .put("counterbore_hole_bridging", process.counterboreHoleBridging.configValue)
            .put("enable_arc_fitting", process.enableArcFitting)
            .put("hole_to_polyhole", process.holeToPolyhole)
            .put("hole_to_polyhole_threshold", process.holeToPolyholeThreshold.ifBlank { "0.01" })
            .put("hole_to_polyhole_twisted", process.holeToPolyholeTwisted)
            .put("precise_outer_wall", process.preciseOuterWall)
            .put("precise_z_height", process.preciseZHeight)
            .put("only_one_wall_first_layer", process.onlyOneWallFirstLayer)
            .put("only_one_wall_top", process.onlyOneWallTopSurfaces)
            .put("is_infill_first", process.printInfillFirst)
            .put("wall_direction", process.wallDirection.configValue)
            .put("print_flow_ratio", process.printFlowRatio.toDouble())
            .put("top_surface_pattern", process.topSurfacePattern.configValue)
            .put("bottom_surface_pattern", process.bottomSurfacePattern.configValue)
            .put("internal_solid_infill_pattern", process.internalSolidInfillPattern.configValue)
            .put("solid_infill_direction", process.solidInfillDirectionDegrees.toDouble())
            .put("solid_infill_rotate_template", process.solidInfillRotateTemplate)
            .put("line_width", process.lineWidth.ifBlank { "0" })
            .put("outer_wall_line_width", process.outerWallLineWidth.ifBlank { "0" })
            .put("inner_wall_line_width", process.innerWallLineWidth.ifBlank { "0" })
            .put("initial_layer_line_width", process.initialLayerLineWidth.ifBlank { "0" })
            .put("initial_layer_min_bead_width", process.initialLayerMinBeadWidthPercent)
            .put("elefant_foot_compensation_layers", process.elefantFootCompensationLayers)
            .put("top_surface_line_width", process.topSurfaceLineWidth.ifBlank { "0" })
            .put("internal_solid_infill_line_width", process.internalSolidInfillLineWidth.ifBlank { "0" })
            .put("min_width_top_surface", process.minWidthTopSurface.ifBlank { "300%" })
            .put("sparse_infill_line_width", process.sparseInfillLineWidth.ifBlank { "0" })
            .put("infill_direction", process.infillDirectionDegrees.toDouble())
            .put("sparse_infill_rotate_template", process.sparseInfillRotateTemplate)
            .put("align_infill_direction_to_model", process.alignInfillDirectionToModel)
            .put("infill_wall_overlap", process.infillWallOverlapPercent)
            .put("top_bottom_infill_wall_overlap", process.topBottomInfillWallOverlapPercent)
            .put("infill_anchor", process.infillAnchor.ifBlank { "400%" })
            .put("infill_anchor_max", process.infillAnchorMax.ifBlank { "20" })
            .put("infill_combination", process.infillCombination)
            .put("infill_combination_max_layer_height", process.infillCombinationMaxLayerHeight.ifBlank { "100%" })
            .put("alternate_extra_wall", process.alternateExtraWall)
            .put("extra_solid_infills", process.extraSolidInfills)
            .put("minimum_sparse_infill_area", process.minimumSparseInfillAreaMm2.toDouble())
            .put("detect_thin_wall", process.detectThinWall)
            .put("detect_overhang_wall", process.detectOverhangWall)
            .put("make_overhang_printable", process.makeOverhangPrintable)
            .put("make_overhang_printable_angle", process.makeOverhangPrintableAngleDegrees.toDouble())
            .put("make_overhang_printable_hole_size", process.makeOverhangPrintableHoleSizeMm2.toDouble())
            .put("overhang_reverse", process.overhangReverse)
            .put("overhang_reverse_internal_only", process.overhangReverseInternalOnly)
            .put("overhang_reverse_threshold", process.overhangReverseThreshold.ifBlank { "50%" })
            .put("thick_bridges", process.thickBridges)
            .put("slice_closing_radius", process.sliceClosingRadiusMm.toDouble())
            .put("resolution", process.resolutionMm.toDouble())
            .put("interface_shells", process.interfaceShells)
            .put("dont_filter_internal_bridges", process.dontFilterInternalBridges.configValue)
            .put("detect_narrow_internal_solid_infill", process.detectNarrowInternalSolidInfill)
            .put("elefant_foot_compensation", process.elefantFootCompensationMm.toDouble())
            .put("apply_top_surface_compensation", process.applyTopSurfaceCompensation)
            .put("ensure_vertical_shell_thickness", process.ensureVerticalShellThickness.configValue)
            .put("wall_generator", process.wallGenerator.configValue)
            .put("wall_transition_angle", process.wallTransitionAngleDegrees.toDouble())
            .put("wall_transition_filter_deviation", process.wallTransitionFilterDeviationPercent)
            .put("wall_transition_length", process.wallTransitionLengthPercent)
            .put("wall_distribution_count", process.wallDistributionCount)
            .put("min_bead_width", process.minBeadWidthPercent)
            .put("min_feature_size", process.minFeatureSizePercent)
            .put("min_length_factor", process.minLengthFactorMm.toDouble())
            .put("wall_infill_order", process.wallInfillOrder.configValue)
            .put("wall_sequence", process.wallSequence.configValue)
            .put("reduce_crossing_wall", process.reduceCrossingWall)
            .put("max_travel_detour_distance", process.maxTravelDetourDistance.ifBlank { "0" })
            .put("extra_perimeters_on_overhangs", process.extraPerimetersOnOverhangs)
            .put("xy_hole_compensation", process.xyHoleCompensationMm.toDouble())
            .put("xy_contour_compensation", process.xyContourCompensationMm.toDouble())
            .put("sparse_infill_density", process.infillPercent)
            .put("sparse_infill_pattern", process.sparseInfillPattern.configValue)
            .put("skin_infill_density", process.skinInfillDensity)
            .put("skeleton_infill_density", process.skeletonInfillDensity)
            .put("infill_lock_depth", process.infillLockDepthMm.toDouble())
            .put("skin_infill_depth", process.skinInfillDepthMm.toDouble())
            .put("skin_infill_line_width", process.skinInfillLineWidth)
            .put("skeleton_infill_line_width", process.skeletonInfillLineWidth)
            .put("symmetric_infill_y_axis", process.symmetricInfillYAxis)
            .put("infill_shift_step", process.infillShiftStepMm.toDouble())
            .put("infill_overhang_angle", process.infillOverhangAngleDegrees.toDouble())
            .put("sparse_infill_filament", process.sparseInfillFilament)
            .put("sparse_infill_flow_ratio", process.sparseInfillFlowRatio.toDouble())
            .put("internal_solid_infill_flow_ratio", process.internalSolidInfillFlowRatio.toDouble())
            .put("set_other_flow_ratios", process.setOtherFlowRatios)
            .put("small_area_infill_flow_compensation", process.smallAreaInfillFlowCompensation)
            .put("lateral_lattice_angle_1", process.lateralLatticeAngle1Degrees.toDouble())
            .put("lateral_lattice_angle_2", process.lateralLatticeAngle2Degrees.toDouble())
            .put("fill_multiline", process.fillMultiline)
            .put("gap_fill_target", process.gapFillTarget)
            .put("filter_out_gap_fill", process.filterOutGapFillMm.toDouble())
            .put("gap_fill_flow_ratio", process.gapFillFlowRatio.toDouble())
            .put("enable_support", process.enableSupport)
            .put("support_type", process.supportType.configValue)
            .put("support_style", process.supportStyle.configValue)
            .put("support_threshold_angle", process.supportThresholdAngleDegrees)
            .put("support_threshold_overlap", process.supportThresholdOverlap.ifBlank { "50%" })
            .put("support_on_build_plate_only", process.supportBuildplateOnly)
            .put("support_critical_regions_only", process.supportCriticalRegionsOnly)
            .put("support_remove_small_overhang", process.supportRemoveSmallOverhang)
            .put("raft_first_layer_density", process.raftFirstLayerDensityPercent)
            .put("raft_first_layer_expansion", process.raftFirstLayerExpansionMm.toDouble())
            .put("raft_layers", process.raftLayers)
            .put("raft_contact_distance", process.raftContactDistanceMm.toDouble())
            .put("raft_expansion", process.raftExpansionMm.toDouble())
            .put("support_filament", process.supportFilament)
            .put("support_interface_filament", process.supportInterfaceFilament)
            .put("support_interface_not_for_body", process.supportInterfaceNotForBody)
            .put("support_top_z_distance", process.supportTopZDistanceMm.toDouble())
            .put("support_bottom_z_distance", process.supportBottomZDistanceMm.toDouble())
            .put("support_interface_top_layers", process.supportInterfaceTopLayers)
            .put("support_interface_bottom_layers", process.supportInterfaceBottomLayers)
            .put("support_interface_spacing", process.supportInterfaceSpacingMm.toDouble())
            .put("support_bottom_interface_spacing", process.supportBottomInterfaceSpacingMm.toDouble())
            .put("support_interface_speed", process.supportInterfaceSpeedMmPerSec.toDouble())
            .put("support_interface_flow_ratio", process.supportInterfaceFlowRatio.toDouble())
            .put("support_material_interface_fan_speed", process.supportMaterialInterfaceFanSpeed.ifBlank { "100%" })
            .put("support_interface_pattern", process.supportInterfacePattern.configValue)
            .put("support_interface_loop_pattern", process.supportInterfaceLoopPattern)
            .put("support_line_width", process.supportLineWidth.ifBlank { "0" })
            .put("support_base_pattern", process.supportBasePattern.configValue)
            .put("support_base_pattern_spacing", process.supportBasePatternSpacingMm.toDouble())
            .put("support_angle", process.supportAngleDegrees.toDouble())
            .put("support_speed", process.supportSpeedMmPerSec.toDouble())
            .put("support_flow_ratio", process.supportFlowRatio.toDouble())
            .put("support_object_elevation", process.supportObjectElevationMm.toDouble())
            .put("support_object_first_layer_gap", process.supportObjectFirstLayerGapMm.toDouble())
            .put("max_bridge_length", process.supportMaxBridgeLengthMm.toDouble())
            .put("support_ironing", process.supportIroning)
            .put("support_ironing_pattern", process.supportIroningPattern.configValue)
            .put("support_ironing_flow", process.supportIroningFlowPercent.orcaSupportIroningFlowPercent().toDouble())
            .put("support_ironing_spacing", process.supportIroningSpacingMm.orcaIroningSpacingMm().toDouble())
            .put("support_expansion", process.supportExpansionMm.toDouble())
            .put("support_object_xy_distance", process.supportObjectXyDistanceMm.toDouble())
            .put("independent_support_layer_height", process.independentSupportLayerHeight)
            .put("tree_support_branch_angle", process.treeSupportBranchAngleDegrees.toDouble())
            .put("tree_support_branch_diameter", process.treeSupportBranchDiameterMm.toDouble())
            .put("tree_support_wall_count", process.treeSupportWallCount)
            .put("tree_support_tip_diameter", process.treeSupportTipDiameterMm.toDouble())
            .put("tree_support_branch_distance", process.treeSupportBranchDistanceMm.toDouble())
            .put("tree_support_branch_distance_organic", process.treeSupportBranchDistanceOrganicMm.toDouble())
            .put("tree_support_top_rate", process.treeSupportTopRatePercent)
            .put("tree_support_branch_diameter_organic", process.treeSupportBranchDiameterOrganicMm.toDouble())
            .put("tree_support_branch_diameter_angle", process.treeSupportBranchDiameterAngleDegrees.toDouble())
            .put("tree_support_branch_angle_organic", process.treeSupportBranchAngleOrganicDegrees.toDouble())
            .put("tree_support_angle_slow", process.treeSupportPreferredBranchAngleDegrees.toDouble())
            .put("tree_support_auto_brim", process.treeSupportAutoBrim)
            .put("tree_support_brim_width", process.treeSupportBrimWidthMm.toDouble())
            .put("ironing_type", process.ironingType.configValue)
            .put("ironing_pattern", process.ironingPattern.configValue)
            .put("ironing_flow", process.ironingFlowPercent.toDouble())
            .put("ironing_spacing", process.ironingSpacingMm.orcaIroningSpacingMm().toDouble())
            .put("ironing_inset", process.ironingInsetMm.toDouble())
            .put("ironing_angle", process.ironingAngleDegrees.toDouble())
            .put("ironing_angle_fixed", process.ironingAngleFixed)
            .put("ironing_speed", process.ironingSpeedMmPerSec.toDouble())
            .put(NativeConfigKeys.PrimeTower.Enable, process.enablePrimeTower)
            .put("prime_tower_width", process.primeTowerWidthMm.toDouble())
            .put(NativeConfigKeys.Process.WipeTowerX, process.wipeTowerXmm.toDouble())
            .put(NativeConfigKeys.Process.WipeTowerY, process.wipeTowerYmm.toDouble())
            .put("prime_tower_skip_points", process.primeTowerSkipPoints)
            .put("prime_volume", process.primeVolumeMm3.toDouble())
            .put("prime_tower_brim_width", process.primeTowerBrimWidthMm.toDouble())
            .put("prime_tower_infill_gap", process.primeTowerInfillGapPercent)
            .put("wipe_tower_rotation_angle", process.wipeTowerRotationAngleDegrees.toDouble())
            .put("wipe_tower_bridging", process.wipeTowerBridgingMm.toDouble())
            .put("wipe_tower_extra_spacing", process.wipeTowerExtraSpacingPercent)
            .put("wipe_tower_extra_flow", process.wipeTowerExtraFlowPercent)
            .put("wipe_tower_max_purge_speed", process.wipeTowerMaxPurgeSpeedMmPerSec.toDouble())
            .put("wipe_tower_wall_type", process.wipeTowerWallType.configValue)
            .put(NativeConfigKeys.Process.WipeTowerConeAngle, process.wipeTowerConeAngleDegrees.toDouble())
            .put("wipe_tower_extra_rib_length", process.wipeTowerExtraRibLengthMm.toDouble())
            .put("wipe_tower_rib_width", process.wipeTowerRibWidthMm.toDouble())
            .put("wipe_tower_fillet_wall", process.wipeTowerFilletWall)
            .put("enable_tower_interface_features", process.enableTowerInterfaceFeatures)
            .put("enable_tower_interface_cooldown_during_tower", process.enableTowerInterfaceCooldownDuringTower)
            .put(NativeConfigKeys.PrimeTower.SingleExtruderMultiMaterialPriming, process.singleExtruderMultiMaterialPriming)
            .put("standby_temperature_delta", process.standbyTemperatureDeltaC)
            .put("wipe_tower_no_sparse_layers", process.wipeTowerNoSparseLayers)
            .put(NativeConfigKeys.PrimeTower.FlushIntoInfill, process.flushIntoInfill)
            .put(NativeConfigKeys.PrimeTower.FlushIntoObjects, process.flushIntoObjects)
            .put(NativeConfigKeys.PrimeTower.FlushIntoSupport, process.flushIntoSupport)
            .put("wall_loops", process.wallCount)
            .put("skirt_type", process.skirtType.configValue)
            .put("skirt_loops", process.skirts)
            .put("skirts", process.skirts)
            .put("min_skirt_length", process.minSkirtLengthMm.toDouble())
            .put("skirt_distance", process.skirtDistanceMm.toDouble())
            .put("skirt_start_angle", process.skirtStartAngleDegrees.toDouble())
            .put("skirt_speed", process.skirtSpeedMmPerSec.toDouble())
            .put("skirt_height", process.skirtHeightLayers)
            .put("draft_shield", process.draftShield.configValue)
            .put("single_loop_draft_shield", process.singleLoopDraftShield)
            .put("brim_type", process.nativeBrimTypeConfigValue())
            .put("brim_width", process.brimWidthMm.toDouble())
            .put("brim_object_gap", process.brimObjectGapMm.toDouble())
            .put("brim_use_efc_outline", process.brimUseEfcOutline)
            .put("combine_brims", process.combineBrims)
            .put("brim_ears", process.brimEars)
            .put("brim_ears_detection_length", process.brimEarsDetectionLengthMm.toDouble())
            .put("brim_ears_max_angle", process.brimEarsMaxAngleDegrees.toDouble())
            .put("slicing_mode", process.slicingMode.configValue)
            .put("print_sequence", process.printSequence.configValue)
            .put("print_order", process.printOrder.configValue)
            .put("spiral_mode", process.spiralMode)
            .put("spiral_mode_smooth", process.spiralModeSmooth)
            .put("spiral_mode_max_xy_smoothing", process.spiralModeMaxXySmoothing.ifBlank { "200%" })
            .put("spiral_starting_flow_ratio", process.spiralStartingFlowRatio.toDouble())
            .put("spiral_finishing_flow_ratio", process.spiralFinishingFlowRatio.toDouble())
            .put("timelapse_type", process.timelapseType.configValue)
            .put("enable_wrapping_detection", process.enableWrappingDetection)
            .put("reduce_infill_retraction", process.reduceInfillRetraction)
            .put("gcode_add_line_number", process.gcodeAddLineNumber)
            .put("gcode_comments", process.gcodeComments)
            .put("gcode_label_objects", process.gcodeLabelObjects)
            .put("exclude_object", process.excludeObject)
            .put(NativeConfigKeys.Filament.MapMode, process.filamentMapMode.configValue)
            .put("allow_mix_temp", process.allowMixTemp)
            .put(NativeConfigKeys.PrimeTower.AllowMulticolorOnePlate, process.allowMulticolorOnePlate)
            .put("filename_format", process.filenameFormat)
            .put("post_process", process.postProcessScripts)
            .put("notes", process.notes)
            .put("fuzzy_skin", process.fuzzySkin.configValue)
            .put("fuzzy_skin_thickness", process.fuzzySkinThicknessMm.toDouble())
            .put("fuzzy_skin_point_distance", process.fuzzySkinPointDistanceMm.toDouble())
            .put("fuzzy_skin_first_layer", process.fuzzySkinFirstLayer)
            .put("fuzzy_skin_mode", process.fuzzySkinMode.configValue)
            .put("fuzzy_skin_noise_type", process.fuzzySkinNoiseType.configValue)
            .put("fuzzy_skin_scale", process.fuzzySkinScaleMm.toDouble())
            .put("fuzzy_skin_octaves", process.fuzzySkinOctaves)
            .put("fuzzy_skin_persistence", process.fuzzySkinPersistence.toDouble())
}

private fun ProcessProfile.nativeBrimTypeConfigValue(): String =
    when {
        brimType == BrimType.Auto && brimWidthMm > 0f -> BrimType.OuterOnly.configValue
        else -> brimType.configValue
    }

private fun Float.orcaIroningSpacingMm(): Float =
    if (this < 0.05f) ORCA_MIN_IRONING_SPACING_MM else this

private fun Float.orcaSupportIroningFlowPercent(): Float =
    if (this <= 0f) ORCA_DEFAULT_SUPPORT_IRONING_FLOW_PERCENT else this

internal fun String.asNativeConfigJsonObjectOrNull(): JSONObject? =
    takeIf { it.isNotBlank() }?.let { raw -> runCatching { JSONObject(raw) }.getOrNull() }

internal fun JSONObject?.nativeResolvedString(key: String): String {
    if (this == null || !has(key) || isNull(key)) return ""
    return when (val value = opt(key)) {
        is JSONArray -> {
            for (index in 0 until value.length()) {
                val scalar = value.opt(index)?.toString()?.trim()?.trim('"').orEmpty()
                if (scalar.isNotBlank() && scalar != "nil") return scalar
            }
            ""
        }
        null -> ""
        else -> value.toString().trim().trim('"').takeUnless { it == "nil" }.orEmpty()
    }
}

internal fun JSONObject?.nativeResolvedDouble(key: String): Double? =
    nativeResolvedString(key).toDoubleOrNull()

internal fun JSONObject?.nativeResolvedBoolean(key: String): Boolean? =
    when (nativeResolvedString(key).trim().lowercase(java.util.Locale.US)) {
        "1", "true", "yes", "on" -> true
        "0", "false", "no", "off" -> false
        else -> null
    }
