#!/usr/bin/env python3
"""Audit Orca/MobileSlicer G-code metadata parity across fixture outputs.

This audit focuses on metadata values that users and printer hosts see outside
the toolpath itself: print time, filament usage, cost, layer count, generator
identity, toolchange commands, and thumbnail block signatures. It intentionally
does not claim toolpath equivalence unless a fixture explicitly has matched
desktop Orca and MobileSlicer outputs.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

import orca_metadata_audit as metadata_audit


DEFAULT_MANIFEST = Path("regression-fixtures/orca-metadata/manifest.json")


PRINT_TIME_RE = re.compile(
    r"estimated print(?:ing)? time(?: \([^)]+\))?\s*=\s*(?P<value>[^;\n\r]+)",
    re.IGNORECASE,
)
FILAMENT_RE = re.compile(
    r";\s*(?P<label>(?:total\s+)?filament used(?: \[[^\]]+\])?|filament used \[[^\]]+\]|total filament cost)"
    r"\s*=\s*(?P<value>.+)",
    re.IGNORECASE,
)
LAYER_COUNT_RE = re.compile(r";\s*(?:total_)?layer_count\s*=\s*(?P<value>\d+)", re.IGNORECASE)
GENERATOR_RE = re.compile(r";\s*generated by\s+(?P<value>.+)", re.IGNORECASE)


@dataclass(frozen=True)
class Drift:
    field: str
    mobile: float | int | str | list[str] | None
    orca: float | int | str | list[str] | None
    absolute_delta: float | None = None
    relative_delta: float | None = None
    threshold: float | None = None
    status: str = "checked"


@dataclass(frozen=True)
class AuditFailure:
    case_id: str
    check: str
    message: str


def repo_path(repo_root: Path, raw_path: str | None) -> Path | None:
    if not raw_path:
        return None
    path = Path(raw_path)
    return path if path.is_absolute() else repo_root / path


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def parse_time_seconds(raw: str) -> int | None:
    text = raw.strip().lower()
    if not text:
        return None
    colon = re.fullmatch(r"(?:(?P<h>\d+):)?(?P<m>\d+):(?P<s>\d+)", text)
    if colon:
        return (
            int(colon.group("h") or 0) * 3600
            + int(colon.group("m")) * 60
            + int(colon.group("s"))
        )
    total = 0
    matched = False
    for number, unit in re.findall(r"(\d+(?:\.\d+)?)\s*(d|day|days|h|hr|hrs|hour|hours|m|min|mins|minute|minutes|s|sec|secs|second|seconds)", text):
        value = float(number)
        if unit.startswith("d"):
            total += int(round(value * 86400))
        elif unit.startswith("h"):
            total += int(round(value * 3600))
        elif unit.startswith("m"):
            total += int(round(value * 60))
        else:
            total += int(round(value))
        matched = True
    return total if matched else None


def parse_number_list(raw: str) -> list[float]:
    values: list[float] = []
    for item in re.split(r"[, ]+", raw.strip()):
        if not item:
            continue
        cleaned = item.strip("$")
        try:
            values.append(float(cleaned))
        except ValueError:
            continue
    return values


def first_print_time_seconds(gcode: str) -> int | None:
    for match in PRINT_TIME_RE.finditer(gcode):
        parsed = parse_time_seconds(match.group("value"))
        if parsed is not None:
            return parsed
    return None


def filament_metrics(gcode: str) -> dict[str, list[float]]:
    metrics: dict[str, list[float]] = {}
    for match in FILAMENT_RE.finditer(gcode):
        label = re.sub(r"\s+", " ", match.group("label").strip().lower())
        values = parse_number_list(match.group("value"))
        if values:
            metrics[label] = values
    return metrics


def first_layer_count(gcode: str) -> int | None:
    for match in LAYER_COUNT_RE.finditer(gcode):
        return int(match.group("value"))
    return None


def generator_markers(gcode: str) -> list[str]:
    markers = [match.group("value").strip() for match in GENERATOR_RE.finditer(gcode)]
    return markers


def inspect_metadata(path: Path) -> dict[str, Any]:
    gcode = read_text(path)
    inspected = metadata_audit.inspect_gcode(path)
    thumbnails = [metadata_audit.thumbnail_signature(block) for block in inspected.thumbnail_blocks]
    return {
        "path": str(path),
        "bytes": path.stat().st_size,
        "lines": inspected.lines,
        "stripped_sha256": inspected.stripped_sha256,
        "print_time_seconds": first_print_time_seconds(gcode),
        "print_time_lines": inspected.print_time_lines,
        "filament": filament_metrics(gcode),
        "filament_lines": inspected.filament_lines,
        "layer_count": first_layer_count(gcode),
        "layer_lines": inspected.layer_lines,
        "toolchange_count": len(inspected.toolchange_lines),
        "toolchange_lines": inspected.toolchange_lines,
        "generator_markers": generator_markers(gcode),
        "thumbnail_signatures": thumbnails,
    }


def compare_numeric(
    field: str,
    mobile: float | int | None,
    orca: float | int | None,
    relative_threshold: float,
) -> Drift:
    if mobile is None or orca is None:
        return Drift(field=field, mobile=mobile, orca=orca, status="missing")
    absolute_delta = abs(float(mobile) - float(orca))
    denominator = max(abs(float(orca)), 1.0)
    relative_delta = absolute_delta / denominator
    return Drift(
        field=field,
        mobile=mobile,
        orca=orca,
        absolute_delta=absolute_delta,
        relative_delta=relative_delta,
        threshold=relative_threshold,
        status="match" if relative_delta <= relative_threshold else "drift",
    )


def compare_list_sum(
    field: str,
    mobile: list[float] | None,
    orca: list[float] | None,
    relative_threshold: float,
) -> Drift:
    if mobile is None or orca is None:
        return Drift(field=field, mobile=mobile, orca=orca, status="missing")
    return compare_numeric(field, sum(mobile), sum(orca), relative_threshold)


def compare_exact(field: str, mobile: Any, orca: Any) -> Drift:
    return Drift(
        field=field,
        mobile=mobile,
        orca=orca,
        status="match" if mobile == orca else "drift",
    )


def compare_thumbnail_signatures(mobile: list[str], orca: list[str]) -> Drift:
    if mobile == orca:
        return Drift(field="thumbnail_signatures", mobile=mobile, orca=orca, status="match")
    if mobile and not orca:
        return Drift(
            field="thumbnail_signatures",
            mobile=mobile,
            orca=orca,
            status="reference_unavailable",
        )
    return Drift(field="thumbnail_signatures", mobile=mobile, orca=orca, status="drift")


def compare_body_hash(mobile: str | None, orca: str | None) -> Drift:
    if mobile == orca:
        return Drift(field="stripped_sha256", mobile=mobile, orca=orca, status="match")
    return Drift(field="stripped_sha256", mobile=mobile, orca=orca, status="body_diff")


def required_gcode_metadata(case: dict[str, Any]) -> tuple[bool, bool, bool]:
    expectations = case.get("expectations", {})
    if not isinstance(expectations, dict):
        return False, False, False
    return (
        bool(expectations.get("require_print_time", False)),
        bool(expectations.get("require_filament", False)),
        bool(expectations.get("require_toolchange", False)),
    )


def evaluate_case(
    repo_root: Path,
    case: dict[str, Any],
    *,
    print_time_threshold: float,
    filament_threshold: float,
    fail_on_drift: bool,
) -> tuple[dict[str, Any], list[AuditFailure]]:
    case_id = str(case.get("id", "<missing>"))
    paths = case.get("paths", {})
    if not isinstance(paths, dict):
        return {"id": case_id, "status": "invalid"}, [
            AuditFailure(case_id, "invalid-manifest-case", "paths must be an object")
        ]
    mobile_path = repo_path(repo_root, paths.get("mobile_gcode"))
    orca_path = repo_path(repo_root, paths.get("orca_gcode"))
    output: dict[str, Any] = {
        "id": case_id,
        "kind": "gcode",
        "paths": {
            "mobile_gcode": str(mobile_path) if mobile_path else None,
            "orca_gcode": str(orca_path) if orca_path else None,
        },
    }
    failures: list[AuditFailure] = []
    if mobile_path is None or not mobile_path.exists():
        output["status"] = "missing-mobile"
        failures.append(AuditFailure(case_id, "missing-mobile-output", f"missing MobileSlicer G-code: {mobile_path}"))
        return output, failures

    mobile = inspect_metadata(mobile_path)
    output["mobile"] = mobile
    require_print_time, require_filament, require_toolchange = required_gcode_metadata(case)
    if require_print_time and mobile["print_time_seconds"] is None:
        failures.append(AuditFailure(case_id, "print-time", "missing or unparsable MobileSlicer print time metadata"))
    if require_filament and not mobile["filament"]:
        failures.append(AuditFailure(case_id, "filament", "missing or unparsable MobileSlicer filament metadata"))
    if require_toolchange and mobile["toolchange_count"] <= 0:
        failures.append(AuditFailure(case_id, "toolchange", "missing MobileSlicer toolchange metadata or commands"))

    if orca_path is None:
        output["status"] = "mobile-contract-only"
        output["drift"] = []
        return output, failures
    if not orca_path.exists():
        output["status"] = "missing-orca-reference"
        failures.append(AuditFailure(case_id, "missing-orca-reference", f"missing Orca G-code reference: {orca_path}"))
        return output, failures

    orca = inspect_metadata(orca_path)
    output["orca"] = orca
    drifts: list[Drift] = [
        compare_numeric(
            "print_time_seconds",
            mobile["print_time_seconds"],
            orca["print_time_seconds"],
            print_time_threshold,
        ),
        compare_thumbnail_signatures(mobile["thumbnail_signatures"], orca["thumbnail_signatures"]),
        compare_body_hash(mobile["stripped_sha256"], orca["stripped_sha256"]),
    ]
    all_filament_keys = sorted(set(mobile["filament"]).union(orca["filament"]))
    for key in all_filament_keys:
        drifts.append(
            compare_list_sum(
                f"filament.{key}",
                mobile["filament"].get(key),
                orca["filament"].get(key),
                filament_threshold,
            )
        )
    output["drift"] = [asdict(drift) for drift in drifts]
    drift_failures = [
        drift for drift in drifts
        if drift.status == "drift"
        and drift.field not in {"thumbnail_signatures", "stripped_sha256"}
    ]
    if fail_on_drift:
        for drift in drift_failures:
            failures.append(
                AuditFailure(
                    case_id,
                    f"metadata-drift-{drift.field}",
                    f"{drift.field} drifted beyond threshold: mobile={drift.mobile} orca={drift.orca}",
                )
            )
    output["status"] = "failed" if failures else "checked"
    return output, failures


def load_manifest(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--case", action="append", default=[], help="run only this manifest case id")
    parser.add_argument("--print-time-relative-threshold", type=float, default=0.05)
    parser.add_argument("--filament-relative-threshold", type=float, default=0.02)
    parser.add_argument(
        "--fail-on-drift",
        action="store_true",
        help="turn desktop-vs-mobile numeric metadata drift into failures",
    )
    parser.add_argument("--pretty", action="store_true")
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    manifest_path = args.manifest if args.manifest.is_absolute() else repo_root / args.manifest
    manifest = load_manifest(manifest_path)
    selected = set(args.case)
    cases = manifest.get("cases", [])
    if not isinstance(cases, list):
        raise SystemExit("manifest cases must be a list")

    outputs: list[dict[str, Any]] = []
    failures: list[AuditFailure] = []
    for case in cases:
        if not isinstance(case, dict):
            failures.append(AuditFailure("<manifest>", "invalid-manifest-case", "case entry must be an object"))
            continue
        if case.get("kind") != "gcode":
            continue
        case_id = str(case.get("id", ""))
        if selected and case_id not in selected:
            continue
        output, case_failures = evaluate_case(
            repo_root,
            case,
            print_time_threshold=args.print_time_relative_threshold,
            filament_threshold=args.filament_relative_threshold,
            fail_on_drift=args.fail_on_drift,
        )
        outputs.append(output)
        failures.extend(case_failures)

    seen = {case["id"] for case in outputs}
    for missing in sorted(selected.difference(seen)):
        failures.append(AuditFailure(missing, "unknown-case", f"manifest has no G-code case {missing!r}"))
        outputs.append({"id": missing, "status": "invalid"})

    drift_count = 0
    compared_cases = 0
    for output in outputs:
        drifts = output.get("drift", [])
        if isinstance(drifts, list) and drifts:
            compared_cases += 1
            drift_count += sum(
                1 for item in drifts
                if isinstance(item, dict) and item.get("status") == "drift"
            )

    payload = {
        "manifest": str(manifest_path),
        "thresholds": {
            "print_time_relative": args.print_time_relative_threshold,
            "filament_relative": args.filament_relative_threshold,
            "fail_on_drift": args.fail_on_drift,
        },
        "cases": outputs,
        "summary": {
            "cases": len(outputs),
            "compared_to_orca": compared_cases,
            "drift_count": drift_count,
            "failures": len(failures),
        },
        "failures": [asdict(failure) for failure in failures],
    }
    json.dump(payload, sys.stdout, indent=2 if args.pretty else None, sort_keys=True)
    sys.stdout.write("\n")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
