from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import orca_gcode_metadata_parity_audit as audit


SCRIPT = Path(__file__).with_name("orca_gcode_metadata_parity_audit.py")


def write_manifest(root: Path, manifest: dict[str, object]) -> Path:
    path = root / "manifest.json"
    path.write_text(json.dumps(manifest), encoding="utf-8")
    return path


def gcode(
    *,
    print_time: str = "21m 6s",
    filament_mm: str = "1219.40",
    filament_cm3: str = "2.93",
    filament_g: str = "0.00",
    thumbnail: bool = False,
    toolchange: bool = False,
) -> str:
    lines = [
        "; generated by OrcaSlicer-compatible MobileSlicer",
        "G1 X1 Y1 E1",
        f"; estimated printing time (normal mode) = {print_time}",
        f"; filament used [mm] = {filament_mm}",
        f"; filament used [cm3] = {filament_cm3}",
        f"; total filament used [g] = {filament_g}",
        "; total filament cost = 0.00",
        "; total_layer_count = 100",
    ]
    if thumbnail:
        lines = [
            "; THUMBNAIL_BLOCK_START",
            "; thumbnail begin 48x48 4",
            "; abcd",
            "; thumbnail end",
            "; THUMBNAIL_BLOCK_END",
            *lines,
        ]
    if toolchange:
        lines.append("T1 ; change extruder")
    return "\n".join(lines) + "\n"


def run_script(root: Path, manifest: Path, *extra: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--repo-root",
            str(root),
            "--manifest",
            str(manifest),
            *extra,
        ],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


class OrcaGcodeMetadataParityAuditTest(unittest.TestCase):
    def test_parse_time_seconds_accepts_orca_styles(self) -> None:
        self.assertEqual(1266, audit.parse_time_seconds("21m 6s"))
        self.assertEqual(13980, audit.parse_time_seconds("3h 53m"))
        self.assertEqual(3723, audit.parse_time_seconds("1:02:03"))
        self.assertEqual(62, audit.parse_time_seconds("00:01:02"))

    def test_mobile_only_contract_passes_required_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "mobile").mkdir()
            (root / "mobile/out.gcode").write_text(gcode(toolchange=True), encoding="utf-8")
            manifest = write_manifest(
                root,
                {
                    "schema_version": 1,
                    "cases": [
                        {
                            "id": "mobile-only",
                            "kind": "gcode",
                            "paths": {"mobile_gcode": "mobile/out.gcode"},
                            "expectations": {
                                "require_print_time": True,
                                "require_filament": True,
                                "require_toolchange": True,
                            },
                        }
                    ],
                },
            )

            result = run_script(root, manifest)

            self.assertEqual(0, result.returncode, result.stdout + result.stderr)
            payload = json.loads(result.stdout)
            self.assertEqual("mobile-contract-only", payload["cases"][0]["status"])
            self.assertEqual(1266, payload["cases"][0]["mobile"]["print_time_seconds"])
            self.assertEqual(0, payload["summary"]["failures"])

    def test_layer_count_ignores_unrelated_layer_count_settings(self) -> None:
        self.assertIsNone(audit.first_layer_count("; interlocking_beam_layer_count = 2\n"))
        self.assertEqual(100, audit.first_layer_count("; total_layer_count = 100\n"))

    def test_generator_markers_do_not_guess_from_object_comments(self) -> None:
        self.assertEqual([], audit.generator_markers("; printing object cube.stl id:1 copy 0\n"))
        self.assertEqual(
            ["OrcaSlicer 2.3.0-compatible MobileSlicer"],
            audit.generator_markers("; generated by OrcaSlicer 2.3.0-compatible MobileSlicer\n"),
        )

    def test_reports_drift_without_failing_by_default(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "mobile").mkdir()
            (root / "references").mkdir()
            (root / "mobile/out.gcode").write_text(gcode(print_time="20m", filament_mm="100"), encoding="utf-8")
            (root / "references/out.gcode").write_text(gcode(print_time="30m", filament_mm="120"), encoding="utf-8")
            manifest = write_manifest(
                root,
                {
                    "schema_version": 1,
                    "cases": [
                        {
                            "id": "drift",
                            "kind": "gcode",
                            "paths": {
                                "mobile_gcode": "mobile/out.gcode",
                                "orca_gcode": "references/out.gcode",
                            },
                            "expectations": {
                                "require_print_time": True,
                                "require_filament": True,
                            },
                        }
                    ],
                },
            )

            result = run_script(root, manifest)

            self.assertEqual(0, result.returncode, result.stdout + result.stderr)
            payload = json.loads(result.stdout)
            statuses = {item["field"]: item["status"] for item in payload["cases"][0]["drift"]}
            self.assertEqual("drift", statuses["print_time_seconds"])
            self.assertEqual("drift", statuses["filament.filament used [mm]"])
            self.assertGreater(payload["summary"]["drift_count"], 0)

    def test_orca_cli_missing_thumbnail_reference_is_not_metadata_drift(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "mobile").mkdir()
            (root / "references").mkdir()
            (root / "mobile/out.gcode").write_text(gcode(thumbnail=True), encoding="utf-8")
            (root / "references/out.gcode").write_text(gcode(thumbnail=False), encoding="utf-8")
            manifest = write_manifest(
                root,
                {
                    "schema_version": 1,
                    "cases": [
                        {
                            "id": "cli-thumbnail-gap",
                            "kind": "gcode",
                            "paths": {
                                "mobile_gcode": "mobile/out.gcode",
                                "orca_gcode": "references/out.gcode",
                            },
                            "expectations": {
                                "require_print_time": True,
                                "require_filament": True,
                            },
                        }
                    ],
                },
            )

            result = run_script(root, manifest)

            self.assertEqual(0, result.returncode, result.stdout + result.stderr)
            payload = json.loads(result.stdout)
            statuses = {item["field"]: item["status"] for item in payload["cases"][0]["drift"]}
            self.assertEqual("reference_unavailable", statuses["thumbnail_signatures"])
            self.assertEqual(0, payload["summary"]["drift_count"])

    def test_fail_on_drift_turns_numeric_drift_into_failure(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "mobile").mkdir()
            (root / "references").mkdir()
            (root / "mobile/out.gcode").write_text(gcode(print_time="20m"), encoding="utf-8")
            (root / "references/out.gcode").write_text(gcode(print_time="30m"), encoding="utf-8")
            manifest = write_manifest(
                root,
                {
                    "schema_version": 1,
                    "cases": [
                        {
                            "id": "strict-drift",
                            "kind": "gcode",
                            "paths": {
                                "mobile_gcode": "mobile/out.gcode",
                                "orca_gcode": "references/out.gcode",
                            },
                            "expectations": {
                                "require_print_time": True,
                                "require_filament": True,
                            },
                        }
                    ],
                },
            )

            result = run_script(root, manifest, "--fail-on-drift")

            self.assertEqual(1, result.returncode, result.stdout + result.stderr)
            payload = json.loads(result.stdout)
            checks = [failure["check"] for failure in payload["failures"]]
            self.assertIn("metadata-drift-print_time_seconds", checks)

    def test_missing_required_metadata_fails(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "mobile").mkdir()
            (root / "mobile/out.gcode").write_text("G1 X1\n", encoding="utf-8")
            manifest = write_manifest(
                root,
                {
                    "schema_version": 1,
                    "cases": [
                        {
                            "id": "missing",
                            "kind": "gcode",
                            "paths": {"mobile_gcode": "mobile/out.gcode"},
                            "expectations": {
                                "require_print_time": True,
                                "require_filament": True,
                            },
                        }
                    ],
                },
            )

            result = run_script(root, manifest)

            self.assertEqual(1, result.returncode, result.stdout + result.stderr)
            payload = json.loads(result.stdout)
            checks = [failure["check"] for failure in payload["failures"]]
            self.assertIn("print-time", checks)
            self.assertIn("filament", checks)


if __name__ == "__main__":
    unittest.main()
